# pyproject.toml
[tool.pytest.ini_options]
env = [
    "KERAS_BACKEND=jax",
]

filterwarnings = [
    "ignore::DeprecationWarning:scitokens.*",
    "ignore::DeprecationWarning:pkg_resources.*",
    "ignore:distutils Version classes are deprecated. Use packaging.version instead.:DeprecationWarning",
    "ignore:pkg_resources is deprecated:DeprecationWarning",
    "ignore:Deprecated call to `pkg_resources.declare_namespace`:DeprecationWarning",
]